name: Run CHC-COMP (smoke test)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: python3 -m pip install --upgrade pip pyyaml ply

      - name: Setup user namespaces
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Download all dependencies
        run: make download-all

      - name: Configure benchmark environment
        run: source benchmark-utils/ci_config.sh

      - name: Set up test benchmark suite
        run: |
          source benchmark-utils/ci_config.sh
          make setup-test

      - name: Run all verifiers
        run: |
          source benchmark-utils/ci_config.sh
          make verify-all

      - name: Process models
        run: |
          source benchmark-utils/ci_config.sh
          make process-all-models

      - name: Validate all models
        run: |
          source benchmark-utils/ci_config.sh
          make validate-all

      - name: Generate result tables
        run: |
          source benchmark-utils/ci_config.sh
          make process-results

      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@22a6ee251d6f13c6ab1ecb200d974f1a6feb1b8d # v4.4.2
        with:
          branch: gh-pages
          folder: results/pages
          single-commit: true
